version: "3.7"

networks:
  traefik:
    name: traefik

services:
  traefik:
    container_name: "traefik"
    image: "traefik:latest"
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
      - "./configs:/etc/traefik/configs"
      - "./.htpasswd:/etc/traefik/.htpasswd"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env_file: .env
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik
