defaultEntryPoints:
  - http

entryPoints:
  web:
    address: ":80"

log:
  level: DEBUG

api:
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: traefik
    defaultRule: 'Host(`{{ env "HOST_DOMAIN_NAME" }}`)'
  file:
    directory: /etc/traefik/configs
    watch: true
